### PR TITLE
Deploy first version to support 3ds max-2020

### PR DESCRIPTION
**Pull request by loonghao**
Hi,

Due to my only have license 3ds max-2020 yet, this version I only tested in 3ds max-2020

### CODE REVIEW

**Comment by loonghao** [comment]
@mottosso Please have a look. Thanks.

**Comment by mottosso** [comment]
I'm unable to test this (no access to 3ds), but I would be happy to make you the maintainer of this project? As a maintainer, you would perform releases and be responsible for the overall quality of the project.

I was going to ask for an example of how to use it, but found that you had already gone the extra mile and made a `gif`, great work!

- https://github.com/pyblish/pyblish-3dsmax/blob/5ba026e589fc957674f8b78279cd0063e3dbe6a0/README.md#quick-demo-in-3dsmax

**Comment by loonghao** [comment]
I honored to be the maintainer of this project.

**Comment by mottosso** [comment]
Welcome aboard. :)

For this first release, I'll need to upload and register the package on PyPI but it would be great if you can still make the GitHub release and include a short description and perhaps one of your gif's.

- https://github.com/pyblish/pyblish-3dsmax/releases

The goal of each release is for the reader to be able to follow along with significant changes to a project at a glance. Here are some examples.

- https://github.com/mottosso/allzpark/releases
- https://github.com/pyblish/pyblish-base/releases

Once you are happy, feel free to make a release and then I'll take care of PyPI. In the future, making a release on GitHub will automatically trigger a release on PyPI.

**Comment by loonghao** [comment]
@mottosso merged and tagged. please help upload to PyPI

**Comment by mottosso** [comment]
Done, thanks @loonghao!

**Pull request merged**
